// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

type MockSNSRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSNSRepositoryMockRecorder
}

type MockSNSRepositoryMockRecorder struct{ mock *MockSNSRepository }

func NewMockSNSRepository(ctrl *gomock.Controller) *MockSNSRepository {
	m := &MockSNSRepository{ctrl: ctrl}
	m.recorder = &MockSNSRepositoryMockRecorder{m}
	return m
}

func (m *MockSNSRepository) EXPECT() *MockSNSRepositoryMockRecorder { return m.recorder }

func (m *MockSNSRepository) Publish(ctx context.Context, topicARN string, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topicARN, message)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockSNSRepositoryMockRecorder) Publish(ctx, topicARN, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSNSRepository)(nil).Publish), ctx, topicARN, message)
}
