// Code generated by MockGen. DO NOT EDIT.
// Source: aws_stuff/internal/repository (interfaces: SNSRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSNSRepository is a mock of SNSRepository interface.
type MockSNSRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSNSRepositoryMockRecorder
}

// MockSNSRepositoryMockRecorder is the mock recorder for MockSNSRepository.
type MockSNSRepositoryMockRecorder struct {
	mock *MockSNSRepository
}

// NewMockSNSRepository creates a new mock instance.
func NewMockSNSRepository(ctrl *gomock.Controller) *MockSNSRepository {
	mock := &MockSNSRepository{ctrl: ctrl}
	mock.recorder = &MockSNSRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSNSRepository) EXPECT() *MockSNSRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSNSRepository) Publish(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSNSRepositoryMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSNSRepository)(nil).Publish), arg0, arg1, arg2)
}
