// Code generated by MockGen. DO NOT EDIT.
// Source: aws_stuff/internal/repository (interfaces: DynamoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "aws_stuff/pkg/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDynamoRepository is a mock of DynamoRepository interface.
type MockDynamoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoRepositoryMockRecorder
}

// MockDynamoRepositoryMockRecorder is the mock recorder for MockDynamoRepository.
type MockDynamoRepositoryMockRecorder struct {
	mock *MockDynamoRepository
}

// NewMockDynamoRepository creates a new mock instance.
func NewMockDynamoRepository(ctrl *gomock.Controller) *MockDynamoRepository {
	mock := &MockDynamoRepository{ctrl: ctrl}
	mock.recorder = &MockDynamoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoRepository) EXPECT() *MockDynamoRepositoryMockRecorder {
	return m.recorder
}

// PutItem mocks base method.
func (m *MockDynamoRepository) PutItem(arg0 context.Context, arg1 models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutItem indicates an expected call of PutItem.
func (mr *MockDynamoRepositoryMockRecorder) PutItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockDynamoRepository)(nil).PutItem), arg0, arg1)
}

// ReplicateItem mocks base method.
func (m *MockDynamoRepository) ReplicateItem(arg0 context.Context, arg1 models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicateItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateItem indicates an expected call of ReplicateItem.
func (mr *MockDynamoRepositoryMockRecorder) ReplicateItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicateItem", reflect.TypeOf((*MockDynamoRepository)(nil).ReplicateItem), arg0, arg1)
}

// ScanCount mocks base method.
func (m *MockDynamoRepository) ScanCount(arg0 context.Context) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanCount", arg0)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanCount indicates an expected call of ScanCount.
func (mr *MockDynamoRepositoryMockRecorder) ScanCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanCount", reflect.TypeOf((*MockDynamoRepository)(nil).ScanCount), arg0)
}
