// Code generated by MockGen. DO NOT EDIT.
// Source: aws_stuff/internal/repository (interfaces: CloudWatchRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCloudWatchRepository is a mock of CloudWatchRepository interface.
type MockCloudWatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCloudWatchRepositoryMockRecorder
}

// MockCloudWatchRepositoryMockRecorder is the mock recorder for MockCloudWatchRepository.
type MockCloudWatchRepositoryMockRecorder struct {
	mock *MockCloudWatchRepository
}

// NewMockCloudWatchRepository creates a new mock instance.
func NewMockCloudWatchRepository(ctrl *gomock.Controller) *MockCloudWatchRepository {
	mock := &MockCloudWatchRepository{ctrl: ctrl}
	mock.recorder = &MockCloudWatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudWatchRepository) EXPECT() *MockCloudWatchRepositoryMockRecorder {
	return m.recorder
}

// PutCountMetric mocks base method.
func (m *MockCloudWatchRepository) PutCountMetric(arg0 context.Context, arg1, arg2 string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutCountMetric", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutCountMetric indicates an expected call of PutCountMetric.
func (mr *MockCloudWatchRepositoryMockRecorder) PutCountMetric(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutCountMetric", reflect.TypeOf((*MockCloudWatchRepository)(nil).PutCountMetric), arg0, arg1, arg2, arg3)
}
