// Code generated by MockGen. DO NOT EDIT.
// Source: aws_stuff/internal/repository (interfaces: SQSRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/sqs/types"
	gomock "github.com/golang/mock/gomock"
)

// MockSQSRepository is a mock of SQSRepository interface.
type MockSQSRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSQSRepositoryMockRecorder
}

// MockSQSRepositoryMockRecorder is the mock recorder for MockSQSRepository.
type MockSQSRepositoryMockRecorder struct {
	mock *MockSQSRepository
}

// NewMockSQSRepository creates a new mock instance.
func NewMockSQSRepository(ctrl *gomock.Controller) *MockSQSRepository {
	mock := &MockSQSRepository{ctrl: ctrl}
	mock.recorder = &MockSQSRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQSRepository) EXPECT() *MockSQSRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSQSRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSQSRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSQSRepository)(nil).Delete), arg0, arg1, arg2)
}

// Receive mocks base method.
func (m *MockSQSRepository) Receive(arg0 context.Context, arg1 string, arg2, arg3, arg4 int32) ([]types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockSQSRepositoryMockRecorder) Receive(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockSQSRepository)(nil).Receive), arg0, arg1, arg2, arg3, arg4)
}

// Send mocks base method.
func (m *MockSQSRepository) Send(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSQSRepositoryMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSQSRepository)(nil).Send), arg0, arg1, arg2)
}
