// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go/service/sqs"
	"github.com/golang/mock/gomock"
)

// MockSQSRepository is a mock of SQSRepository interface.
type MockSQSRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSQSRepositoryMockRecorder
}

type MockSQSRepositoryMockRecorder struct{ mock *MockSQSRepository }

func NewMockSQSRepository(ctrl *gomock.Controller) *MockSQSRepository {
	m := &MockSQSRepository{ctrl: ctrl}
	m.recorder = &MockSQSRepositoryMockRecorder{m}
	return m
}

func (m *MockSQSRepository) EXPECT() *MockSQSRepositoryMockRecorder { return m.recorder }

func (m *MockSQSRepository) Receive(ctx context.Context, queueURL string, maxMessages int64, visibilityTimeoutSeconds int64, waitTimeSeconds int64) ([]*sqs.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, queueURL, maxMessages, visibilityTimeoutSeconds, waitTimeSeconds)
	ret0, _ := ret[0].([]*sqs.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockSQSRepositoryMockRecorder) Receive(ctx, queueURL, maxMessages, vis, wait interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockSQSRepository)(nil).Receive), ctx, queueURL, maxMessages, vis, wait)
}

func (m *MockSQSRepository) Delete(ctx context.Context, queueURL string, receiptHandle string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, queueURL, receiptHandle)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockSQSRepositoryMockRecorder) Delete(ctx, queueURL, receiptHandle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSQSRepository)(nil).Delete), ctx, queueURL, receiptHandle)
}

func (m *MockSQSRepository) Send(ctx context.Context, queueURL string, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, queueURL, body)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockSQSRepositoryMockRecorder) Send(ctx, queueURL, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSQSRepository)(nil).Send), ctx, queueURL, body)
}
