// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"aws_stuff/pkg/models"
)

// MockDynamoRepository is a mock of DynamoRepository interface.
type MockDynamoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoRepositoryMockRecorder
}

// MockDynamoRepositoryMockRecorder is the mock recorder for MockDynamoRepository.
type MockDynamoRepositoryMockRecorder struct {
	mock *MockDynamoRepository
}

// NewMockDynamoRepository creates a new mock instance.
func NewMockDynamoRepository(ctrl *gomock.Controller) *MockDynamoRepository {
	mock := &MockDynamoRepository{ctrl: ctrl}
	mock.recorder = &MockDynamoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoRepository) EXPECT() *MockDynamoRepositoryMockRecorder { return m.recorder }

// PutItem mocks base method.
func (m *MockDynamoRepository) PutItem(ctx context.Context, item models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutItem indicates an expected call of PutItem.
func (mr *MockDynamoRepositoryMockRecorder) PutItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockDynamoRepository)(nil).PutItem), ctx, item)
}

// ScanCount mocks base method.
func (m *MockDynamoRepository) ScanCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanCount indicates an expected call of ScanCount.
func (mr *MockDynamoRepositoryMockRecorder) ScanCount(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanCount", reflect.TypeOf((*MockDynamoRepository)(nil).ScanCount), ctx)
}

// ReplicateItem mocks base method.
func (m *MockDynamoRepository) ReplicateItem(ctx context.Context, item models.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicateItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateItem indicates an expected call of ReplicateItem.
func (mr *MockDynamoRepositoryMockRecorder) ReplicateItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicateItem", reflect.TypeOf((*MockDynamoRepository)(nil).ReplicateItem), ctx, item)
}
