// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

type MockCloudWatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCloudWatchRepositoryMockRecorder
}

type MockCloudWatchRepositoryMockRecorder struct{ mock *MockCloudWatchRepository }

func NewMockCloudWatchRepository(ctrl *gomock.Controller) *MockCloudWatchRepository {
	m := &MockCloudWatchRepository{ctrl: ctrl}
	m.recorder = &MockCloudWatchRepositoryMockRecorder{m}
	return m
}

func (m *MockCloudWatchRepository) EXPECT() *MockCloudWatchRepositoryMockRecorder { return m.recorder }

func (m *MockCloudWatchRepository) PutCountMetric(ctx context.Context, namespace string, metricName string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutCountMetric", ctx, namespace, metricName, value)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCloudWatchRepositoryMockRecorder) PutCountMetric(ctx, namespace, metricName, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutCountMetric", reflect.TypeOf((*MockCloudWatchRepository)(nil).PutCountMetric), ctx, namespace, metricName, value)
}
