// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

type MockS3Repository struct {
	ctrl     *gomock.Controller
	recorder *MockS3RepositoryMockRecorder
}

type MockS3RepositoryMockRecorder struct{ mock *MockS3Repository }

func NewMockS3Repository(ctrl *gomock.Controller) *MockS3Repository {
	m := &MockS3Repository{ctrl: ctrl}
	m.recorder = &MockS3RepositoryMockRecorder{m}
	return m
}

func (m *MockS3Repository) EXPECT() *MockS3RepositoryMockRecorder { return m.recorder }

func (m *MockS3Repository) GetObjectString(ctx context.Context, bucket string, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectString", ctx, bucket, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockS3RepositoryMockRecorder) GetObjectString(ctx, bucket, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectString", reflect.TypeOf((*MockS3Repository)(nil).GetObjectString), ctx, bucket, key)
}
